// GENERATED by tools/extract-family.js from v95's curriculum.js. Do not edit by hand.
// v95's family-email language: the plain phrase for each Reveal lesson (FAM_MATH), the
// reading strategies and skills in families' words (FAM_META, FAM_COMP), the line merging
// (famSummary), and the spelling-list reader. Copied, not retyped, so the wording is v95's.
(function () {
  function famPhrase(t) {
    var x = String(t || "").trim().replace(/^I can\s+/i, "").replace(/[.\s]+$/, "");
    return x ? x.charAt(0).toUpperCase() + x.slice(1) : "";
  }
  function uniq(a) { var o = []; a.forEach(function (x) { if (x && o.indexOf(x) < 0) o.push(x); }); return o; }

  /* ---- in families' words (v68) ----
     The teacher asked for Math in parent-friendly language, summarised,
     rather than the guide's "I can" targets one per line ("Identify
     patterns when skip counting by 5s"). Each lesson has a plain phrase
     here, written as the middle of a sentence; the week's phrases are
     merged into one line (see famSummary). A lesson missing from this
     table falls back to its first "I can", so nothing is ever dropped. */
  var FAM_MATH = {
    "1|1": "sharing our own math stories", "1|2": "making sense of problems and trying different ways to solve them",
    "1|3": "using math to describe real-life situations", "1|4": "explaining our thinking",
    "1|5": "finding and continuing patterns", "1|6": "working well on our own and in groups",
    "2|1": "seeing how 10 tens make 100", "2|2": "learning what each digit means in a 3-digit number",
    "2|3": "reading and writing numbers up to 1,000", "2|4": "breaking 3-digit numbers into hundreds, tens, and ones in different ways",
    "2|5": "comparing 3-digit numbers",
    "3|1": "counting by 1s up to 1,000", "3|2": "skip counting by 5s", "3|3": "skip counting by 10s and 100s",
    "3|4": "learning about even and odd numbers", "3|5": "showing even numbers as doubles (like 4 + 4)",
    "3|6": "skip counting to find the total in an array (objects set out in rows)", "3|7": "writing addition equations to match an array",
    "4|1": "solving adding-on word problems", "4|2": "solving taking-away word problems",
    "4|3": "working through two-step problems that add on and take away",
    "4|4": "solving putting-together word problems", "4|5": "solving taking-apart word problems",
    "4|6": "working through two-step problems that put together and take apart",
    "4|7": "solving comparing word problems (finding the bigger amount)", "4|8": "solving comparing word problems (finding the smaller amount)",
    "4|9": "working through two-step comparing problems", "4|10": "working through two-step word problems with addition and subtraction",
    "5|1": "adding within 20 by counting on", "5|2": "adding within 20 using other quick strategies",
    "5|3": "adding 2-digit numbers with base-ten blocks", "5|4": "learning that numbers can be added in any order",
    "5|5": "breaking both numbers into tens and ones to add", "5|6": "using a number line to add",
    "5|7": "breaking just one number apart to add", "5|8": "changing numbers into friendlier ones to add",
    "5|9": "adding three or more 2-digit numbers", "5|10": "solving one-step and two-step addition word problems",
    "6|1": "subtracting within 20 by counting up or back", "6|2": "subtracting within 20 by making a 10",
    "6|3": "subtracting 2-digit numbers with base-ten blocks", "6|4": "regrouping to subtract 2-digit numbers (sometimes called borrowing)",
    "6|5": "using a number line to subtract", "6|6": "breaking numbers apart to subtract",
    "6|7": "changing numbers into friendlier ones to subtract", "6|8": "using addition to solve subtraction",
    "6|9": "solving one-step subtraction word problems", "6|10": "solving two-step subtraction word problems",
    "7|1": "measuring length in inches", "7|2": "measuring length in feet and yards",
    "7|3": "comparing lengths in inches, feet, and yards", "7|4": "learning how inches, feet, and yards are related",
    "7|5": "estimating length in inches, feet, and yards using everyday objects",
    "7|6": "measuring length in centimeters and meters", "7|7": "comparing lengths in centimeters and meters",
    "7|8": "learning how centimeters and meters are related", "7|9": "estimating length in centimeters and meters using everyday objects",
    "7|10": "solving word problems about length", "7|11": "solving length problems on a number line",
    "8|1": "learning what each coin is worth", "8|2": "counting a mix of coins",
    "8|3": "counting money with dollar bills and coins", "8|4": "telling time to the nearest five minutes",
    "8|5": "knowing whether a time is a.m. or p.m.",
    "9|1": "adding 10 or 100 in our heads", "9|2": "adding 3-digit numbers without regrouping",
    "9|3": "adding 3-digit numbers with regrouping (sometimes called carrying)",
    "9|4": "breaking 3-digit numbers into hundreds, tens, and ones to add", "9|5": "breaking just one number apart to add 3-digit numbers",
    "9|6": "changing numbers into friendlier ones to add", "9|7": "explaining our addition strategies",
    "10|1": "subtracting 10 or 100 in our heads", "10|2": "subtracting 3-digit numbers without regrouping",
    "10|3": "counting back to subtract 3-digit numbers", "10|4": "counting up to subtract 3-digit numbers",
    "10|5": "regrouping tens to subtract 3-digit numbers", "10|6": "regrouping tens and hundreds to subtract 3-digit numbers",
    "10|7": "changing numbers into friendlier ones to subtract", "10|8": "explaining our subtraction strategies",
    "10|9": "solving word problems with addition and subtraction",
    "11|1": "making picture graphs", "11|2": "making bar graphs", "11|3": "solving problems with bar graphs",
    "11|4": "measuring objects to collect data", "11|5": "reading line plots", "11|6": "making line plots",
    "12|1": "recognizing flat (2-D) shapes", "12|2": "drawing flat (2-D) shapes", "12|3": "recognizing solid (3-D) shapes",
    "12|4": "finding equal shares", "12|5": "splitting shapes into halves, thirds, and fourths",
    "12|6": "splitting rectangles into rows and columns of equal squares"
  };
  function famMath(st) {
    var p = FAM_MATH[st.u + "|" + st.n];
    if (p) return p;
    var t = famPhrase((st.tg || [])[0]) || st.t || "";
    return t.charAt(0).toLowerCase() + t.slice(1);
  }
  /* Consecutive phrases that open (and maybe close) the same way become
     one: "skip counting by 5s" + "skip counting by 10s and 100s" is "skip
     counting by 5s, 10s, and 100s", "making picture graphs" + "making bar
     graphs" is "making picture and bar graphs". They must share two or
     more words at the start, or share words and differ by single words
     only ("reading" / "making" line plots); anything else stays as
     written, so "counting a mix of coins" never runs into "counting
     money with dollar bills". */
  function listJoin(a) {
    if (a.length < 2) return a.join("");
    var sep = a.some(function (x) { return /, /.test(x); }) ? "; " : ", ";
    return a.length === 2 ? a[0] + " and " + a[1] : a.slice(0, -1).join(sep) + sep + "and " + a[a.length - 1];
  }
  function mergeMids(mids) {
    /* "10s and 100s", "inches, feet, and yards": single words run together */
    var flat = [], single = true;
    mids.forEach(function (m) {
      var parts = m.split(/,\s*(?:and\s+)?|\s+and\s+/);
      if (parts.some(function (x) { return !x || /\s/.test(x); })) single = false;
      flat = flat.concat(parts);
    });
    return single ? uniq(flat) : mids;
  }
  function oneWords(m) { return m.split(/,\s*(?:and\s+)?|\s+and\s+/).every(function (x) { return x && !/\s/.test(x); }); }
  function famSummary(phrases) {
    var groups = [];
    phrases.forEach(function (ph) {
      var w = ph.split(" "), g = groups[groups.length - 1];
      if (g) {
        if (g.pre != null) {
          var n = w.length - g.pre - g.suf;
          var mid = w.slice(g.pre, w.length - g.suf).join(" ");
          if (n > 0 && w.slice(0, g.pre).join(" ") === g.head && w.slice(w.length - g.suf).join(" ") === g.tail && (g.pre >= 2 || oneWords(mid))) {
            g.mids.push(mid); return;
          }
        } else {
          var a = g.words, pre = 0, suf = 0;
          while (pre < a.length && pre < w.length && a[pre] === w[pre]) pre++;
          while (suf < a.length - pre && suf < w.length - pre && a[a.length - 1 - suf] === w[w.length - 1 - suf]) suf++;
          var m1 = a.slice(pre, a.length - suf).join(" "), m2 = w.slice(pre, w.length - suf).join(" ");
          if (pre + suf >= 2 && m1 && m2 && (pre >= 2 || (oneWords(m1) && oneWords(m2)))) {
            g.pre = pre; g.suf = suf; g.head = a.slice(0, pre).join(" "); g.tail = a.slice(a.length - suf).join(" ");
            g.mids = [a.slice(pre, a.length - suf).join(" "), w.slice(pre, w.length - suf).join(" ")];
            return;
          }
        }
      }
      groups.push({ words: w, pre: null });
    });
    var out = groups.map(function (g) {
      if (g.pre == null) return g.words.join(" ");
      return [g.head, listJoin(mergeMids(g.mids)), g.tail].filter(Boolean).join(" ");
    });
    var s = listJoin(out);
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
  /* Reading's one goal for the week. v68 picked it; v69, the teacher's
     call: both columns are skills the class works on all week, and he
     picks whichever is most useful for families to practise at home. So
     the sheet lists every one of the week's metacognitive and fix-up
     strategies and comprehension strategies in plain words, and he
     chooses. Until he does, the default is v68's: the first metacognitive
     strategy, or in Units 7 to 10 (which only say "Apply Strategies"
     there) the first comprehension strategy. */
  var FAM_META = [
    [/^Metacognitive: Ask Questions About Characters/, "Asking questions about the characters and events in stories"],
    [/^Metacognitive: Ask Questions/, "Asking questions as we read to help us understand"],
    [/^Metacognitive: Create Mental Images of Characters/, "Picturing the characters and events in stories to help us understand them"],
    [/^Metacognitive: Create Mental Images/, "Making mental images to help us understand what we read"],
    [/^Metacognitive: Draw Inferences/, "Making inferences: using clues to figure out what the author doesn\u2019t say outright"],
    [/^Metacognitive: Make Connections/, "Making connections between what we read and our own lives"],
    [/^Metacognitive: Distinguish Between Important/, "Picking out the most important ideas in what we read"],
    [/^Metacognitive: Summarize/, "Summing up what we read in our own words"],
    [/^Fix-Up: Reread/, "Rereading when something doesn\u2019t make sense"],
    [/^Fix-Up: Read On/, "Reading on to clear up a confusing part"],
    [/^Fix-Up: Stop and Think About the Author/, "Stopping to think about why the author wrote something"],
    [/^Fix-Up: Read Out Loud/, "Reading out loud to help us understand"],
    [/^Fix-Up: Read More Slowly/, "Slowing down and thinking about the words"]
  ];
  var FAM_COMP = [
    [/^Identify Main Topic/, "Finding the main topic and key details in what we read"],
    [/^Explain How Images/, "Using pictures and photos to help us understand what we read"],
    [/^Recount Stories.*\(Recount/, "Retelling stories and finding their lesson or message"],
    [/^Recount Stories/, "Figuring out the lesson or message of a story"],
    [/^Describe the Overall Structure/, "Noticing how a story begins, builds, and ends"],
    [/^Compare and Contrast/, "Comparing the most important points in two texts on the same topic"],
    [/^Introduce Poetry/, "Reading poetry"],
    [/^Describe How Characters Respond/, "Talking about how characters respond to big events and challenges"],
    [/^Use Illustrations and Words/, "Using the words and pictures to understand characters, setting, and plot"],
    [/^Describe a Connection/, "Connecting the events, ideas, or steps in what we read"],
    [/^Acknowledge Differences in the Points of View/, "Noticing how different characters see things differently"],
    [/^Compare Two Versions/, "Comparing two versions of the same story"],
    [/^Identify Main Purpose/, "Figuring out why an author wrote a text"],
    [/^Distinguish Between Important/, "Picking out the most important ideas in what we read"],
    [/^Ask and Answer Questions/, "Asking and answering questions about the key details in what we read"],
    [/^Use Text Features/, "Using headings, captions, and other text features to find facts"],
    [/^Analyze How the Author/, "Looking at the reasons an author gives to support their points"]
  ];
  function famLookup(table, t) {
    for (var i = 0; i < table.length; i++) if (table[i][0].test(t)) return table[i][1];
    return null;
  }
  function famComp(c) {
    var poem = /^Read a Poem: Understand (.+)$/.exec(c);
    return poem ? "Reading poems and noticing " + poem[1].toLowerCase() : famLookup(FAM_COMP, c) || c;
  }
  /* [{ src, t, col }]: src is the scope and sequence's own wording, which
     is what a choice is saved as; the default comes first in its column */
  function famGoalOptions(w) {
    var o = [], seen = {};
    function add(src, t, col) { if (t && !seen[t]) { seen[t] = 1; o.push({ src: src, t: t, col: col }); } }
    (w.meta || []).forEach(function (x) { if (!/Apply/.test(x)) add(x, famLookup(FAM_META, x), "meta"); });
    (w.comp || []).forEach(function (x) { add(x, famComp(x), "comp"); });
    return o;
  }
  function famGoalDefault(opts) {
    return opts.filter(function (x) { return x.col === "meta" && /^Metacognitive:/.test(x.src); })[0] ||
      opts.filter(function (x) { return x.col === "comp"; })[0] || opts[0] || null;
  }

  function parseSpelling(t) {
    return uniq(String(t || "").split(/[\n,;\t]+/).map(function (x) {
      return x.replace(/^\s*(?:\d+\s*[.):-]|[-\u2022*\u00b7])\s*/, "").trim();
    }).filter(Boolean));
  }
  function spellLine(words) { return "Spelling words to practice at home: " + words.join(", "); }

  const api = { famPhrase, uniq, famMath, famSummary, famLookup, famComp, famGoalOptions, famGoalDefault, parseSpelling, spellLine, FAM_MATH, FAM_META, FAM_COMP };
  if (typeof module !== 'undefined') module.exports = api;
  if (typeof window !== 'undefined') window.SuiteFamilyV95 = api;
})();
