// GENERATED by tools/extract-subplan.js from v95's sub-plans.js. Do not edit by hand.
// v95's sub plan printouts, copied unchanged. make(env) gives them the day's data (see core/subplan.js).
(function () {
  function make(env) {
    var S = env.S, blocksFor = env.blocksFor, lessonFor = env.lessonFor, dayNote = env.dayNote, dayFlags = env.dayFlags,
      dayBlockNotes = env.dayBlockNotes, blockNoteFor = env.blockNoteFor, bkey = env.bkey, mathBoard = env.mathBoard;
    var window = { SuiteWin: env.win || null };
  var DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  var MONTHS = ["January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"];
  var DAYKEY = ["U", "M", "T", "W", "R", "F", "S"];
  var DOC_CSS =
    "@page{margin:14mm}" +
    "#subprint{font-family:'IBM Plex Sans','Segoe UI',system-ui,sans-serif;color:#14202A;font-size:11.5pt;line-height:1.45}" +
    "#subprint h1{font-family:'IBM Plex Serif',Georgia,serif;font-size:19pt;margin:0 0 2pt}" +
    "#subprint h2{font-size:11pt;letter-spacing:.09em;text-transform:uppercase;color:#55636E;margin:16pt 0 6pt;border-bottom:1px solid #C9D1D8;padding-bottom:3pt}" +
    "#subprint .lede{color:#55636E;margin:0 0 12pt;font-size:11pt}" +
    "#subprint .blk{page-break-inside:avoid;margin:0 0 11pt;padding-left:10pt;border-left:2.5pt solid #C9D1D8}" +
    "#subprint .blk .t{font-size:10.5pt;color:#55636E;font-weight:600}" +
    "#subprint .blk .h{font-size:13pt;font-weight:600;margin:1pt 0 3pt}" +
    "#subprint .blk .w{display:inline-block;padding:1.5pt 6pt;border:1px solid #C9D1D8;border-radius:4pt;font-size:10pt;margin-bottom:4pt}" +
    "#subprint .blk p{margin:3pt 0}" +
    "#subprint .em{background:#FAF2E2;border:1px solid #E7D7B4;border-radius:4pt;padding:5pt 8pt;font-size:10.5pt;margin-top:5pt}" +
    "#subprint .em b{color:#8A5E14}" +
    "#subprint .box{border:1px solid #C9D1D8;border-radius:5pt;padding:8pt 10pt;margin:0 0 9pt}" +
    "#subprint .two{display:flex;gap:12pt}#subprint .two>*{flex:1}" +
    "#subprint table{width:100%;border-collapse:collapse;font-size:10.5pt}" +
    "#subprint th,#subprint td{border:1px solid #C9D1D8;padding:4pt 6pt;text-align:left;vertical-align:top}" +
    "#subprint th{background:#EDF0F2;font-size:9.5pt;letter-spacing:.06em;text-transform:uppercase}" +
    "#subprint .sig{font-size:12.5pt;font-weight:600}" +
    "#subprint .notes{border:1px solid #C9D1D8;border-radius:5pt;height:150pt;margin-top:6pt}" +
    "#subprint .muted{color:#55636E}";

  function esc(x) {
    return String(x == null ? "" : x).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  function nl(x) { return esc(x).replace(/\n/g, "<br>"); }

  function dayKeyOf(iso) { var d = new Date(iso + "T12:00:00"); return isNaN(d) ? "M" : DAYKEY[d.getDay()]; }

  function pretty(iso) {
    var d = new Date(iso + "T12:00:00");
    if (isNaN(d)) return iso;
    return ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][d.getDay()] +
      ", " + d.getDate() + " " + MONTHS[d.getMonth()];
  }

  function when(b) { return b.end ? esc(b.start) + " – " + esc(b.end) : esc(b.start); }

  function justToday(iso) {
    var onDay = {};
    blocksFor(iso).forEach(function (b) { if (b.key) onDay[b.key] = true; });
    var note = dayNote(iso), flags = dayFlags(iso), h = "";
    /* v94: a note on a block prints on that block; one whose block is gone prints here */
    var blk = dayBlockNotes(iso).filter(function (x) { return !onDay[bkey(x.t, x.l)]; });
    if (!note && !flags.length && !blk.length) return "";
    if (flags.length) h += "<p><b>Heads up today:</b> " + esc(flags.join(" · ")) + "</p>";
    if (note) h += nl(note);
    blk.forEach(function (x) { h += "<p><b>" + esc(x.l) + (x.t ? " (" + esc(x.t) + ")" : "") + ":</b> " + nl(x.note) + "</p>"; });
    return '<div class="box">' + h + "</div>";
  }

  function specialFor(iso, title) {
    var pair = S.specials[dayKeyOf(iso)];
    if (!pair) return "";
    /* v94: "Specials 2 \u2014 PE", from the planner, already says what it is */
    if (/\u2014|\s-\s/.test(String(title || ""))) return "";
    if (/specials\s*1/i.test(title)) return pair[0] || "";
    if (/specials\s*2/i.test(title)) return pair[1] || "";
    return "";
  }

  function firstSentence(t) {
    var s = String(t || "").replace(/\s+/g, " ").trim();
    var m = s.match(/^(.{0,150}?[.!?])\s/);
    return m ? m[1] : (s.length > 150 ? s.slice(0, 147) + "…" : s);
  }

  function groupsHTML(iso, brief) {
    var h = "", mb = mathBoard(), w = window.SuiteWin ? window.SuiteWin.forDay(iso) : null;
    if (mb) {
      h += "<h2>" + esc(mb.title) + "</h2>" + (brief ? "" : "<p>Each group starts at the station shown and rotates on the signal.</p>") +
        '<table><thead><tr><th style="width:22%">Group</th><th style="width:22%">Starts at</th><th>Students</th></tr></thead><tbody>' +
        mb.groups.map(function (g) { return "<tr><td><b>" + esc(g.name) + "</b></td><td>" + esc(g.station) + "</td><td>" + esc(g.names.join(", ") || "\u2014") + "</td></tr>"; }).join("") +
        "</tbody></table>";
    }
    if (w) {
      h += "<h2>" + esc(w.subject) + "</h2>";
      var away = w.ours.filter(function (x) { return x.goes !== "stays in our room"; });
      h += "<p>For Walk to WIN, each of our students goes to their " + esc(w.word.toLowerCase()) + " group." +
        (w.me ? " " + esc(w.me) + "\u2019s group meets in our room." : "") + "</p>";
      h += '<table><thead><tr><th style="width:30%">Student</th><th>Goes to</th></tr></thead><tbody>' +
        w.ours.map(function (x) { return "<tr><td>" + esc(x.name) + "</td><td>" + esc(x.goes) + "</td></tr>"; }).join("") + "</tbody></table>";
      /* only the children from other classes: ours who stay are in the table */
      w.coming = w.coming.filter(function (r) { return !r.ours; });
      if (w.coming.length && !brief) {
        h += "<p><b>Coming to our room (" + w.coming.length + "):</b> " + w.coming.map(function (r) { return esc(r.name) + (r.note ? " (" + esc(r.note) + ")" : ""); }).join(", ") + "</p>";
      } else if (w.coming.length) h += "<p><b>Coming to our room:</b> " + w.coming.length + " students \u2014 the list is in the full plan.</p>";
    }
    return h;
  }

  function buildFull(iso, who) {
    var h = "<h1>Sub plans &middot; " + esc(pretty(iso)) + "</h1>";
    h += '<p class="lede">' + esc(who || "Grade 2") + (S.contact ? " &middot; reach me at " + esc(S.contact) : "") + "</p>";
    if (S.intro) h += '<div class="box">' + nl(S.intro) + "</div>";
    if (S.signal || S.trusted) {
      h += "<h2>First things</h2>";
      if (S.signal) h += '<p class="sig">' + nl(S.signal) + "</p>";
      if (S.trusted) h += "<p><b>Students who can tell you how things run:</b> " + esc(S.trusted) + "</p>";
    }
    if (S.arrival) h += "<h2>Arrival</h2><p>" + nl(S.arrival) + "</p>";
    var today = justToday(iso);
    if (today) h += "<h2>Just for this day</h2>" + today;

    h += "<h2>The day, block by block</h2>";
    var blocks = blocksFor(iso);
    if (!blocks.length) h += "<p>No blocks are set for a " + esc(DAYS[new Date(iso + "T12:00:00").getDay()]) + ".</p>";
    /* A subject note is written once per day but Reading has three blocks,
       so it printed three times. It goes on the first block for the subject,
       the way the planner's own timeline does it. */
    var noted = {};
    blocks.forEach(function (b) {
      var l = lessonFor(iso, b.subject), sp = specialFor(iso, b.title);
      h += '<div class="blk"><div class="t">' + when(b) + "</div>";
      h += '<div class="h">' + esc(b.title) + (sp ? ": " + esc(sp) : "") + "</div>";
      if (l && !l.taught) {
        h += '<p class="muted"><b>Not happening today.</b> ' + esc(l.name) + " is skipped in my plan for this day" +
          (today ? " &mdash; see Just for this day." : ".") + "</p></div>";
        return;
      }
      if (l && l.where) h += '<span class="w"><b>' + esc(l.label) + "</b> &middot; " + esc(l.where) + "</span>";
      var tnote = blockNoteFor(iso, b);                                        /* v94 */
      if (tnote) h += '<p class="today"><b>Today:</b> ' + nl(tnote) + "</p>";
      if (b.standing) h += "<p>" + nl(b.standing) + "</p>";
      if (l && !noted["rv|" + b.subject]) {
        noted["rv|" + b.subject] = true;
        if (l.targets && l.targets.length) h += "<p><b>Learning targets:</b> " + esc(l.targets.join(" ")) + "</p>";
        if (l.materials && l.materials.length) h += "<p><b>Materials:</b> " + esc(l.materials.join(", ")) + "</p>";
      }
      if (l && l.note && !noted[b.subject]) { noted[b.subject] = true; h += "<p><b>My note:</b> " + nl(l.note) + "</p>"; }
      if (l && l.free && !l.where && !l.note) h += '<p class="muted">Nothing is written for this block today.</p>';
      if (b.detail) h += "<p>" + nl(b.detail) + "</p>";
      if (b.emergency) h += '<div class="em"><b>If you cannot find it:</b> ' + nl(b.emergency) + "</div>";
      h += "</div>";
    });

    h += groupsHTML(iso, false);                                  /* v89 */

    if (S.incentives || S.consequences || S.watch.length) {
      h += "<h2>Behaviour</h2>";
      if (S.incentives) h += "<p>" + nl(S.incentives) + "</p>";
      if (S.consequences) h += "<p>" + nl(S.consequences) + "</p>";
      if (S.watch.length) {
        h += '<table><thead><tr><th style="width:22%">Student</th><th>What helps</th></tr></thead><tbody>' +
          S.watch.map(function (w) { return "<tr><td><b>" + esc(w.name) + "</b></td><td>" + nl(w.note) + "</td></tr>"; }).join("") +
          "</tbody></table>";
      }
    }
    if (S.closing) h += "<h2>End of day</h2><p>" + nl(S.closing) + "</p>";
    h += '<h2>How did it go?</h2><div class="notes"></div>';
    return h;
  }

  function buildGlance(iso, who) {
    var h = "<h1>At a glance &middot; " + esc(pretty(iso)) + "</h1>";
    h += '<p class="lede">' + esc(who || "Grade 2") + (S.contact ? " &middot; " + esc(S.contact) : "") + " &middot; the full plan has the detail</p>";
    if (S.signal) h += '<div class="box"><b>To get their attention:</b> <span class="sig">' + esc(S.signal).replace(/\n/g, " ") + "</span></div>";
    h += '<h2>The day</h2><table><thead><tr><th style="width:15%">Time</th><th style="width:32%">What</th><th>Where it is</th></tr></thead><tbody>';
    blocksFor(iso).forEach(function (b) {
      var l = lessonFor(iso, b.subject), sp = specialFor(iso, b.title);
      var off = !!(l && !l.taught);
      var cell = off ? '<span class="muted">Not happening today</span>'
        : l && l.where ? esc(l.label + " · " + l.where)
        : '<span class="muted">—</span>';
      h += "<tr><td>" + (b.end ? esc(b.start) + "–" + esc(b.end) : esc(b.start)) + "</td><td><b>" + esc(b.title) + (sp ? ": " + esc(sp) : "") + "</b></td><td>" +
        cell + (blockNoteFor(iso, b) && !off ? "<br><b>Today:</b> " + esc(firstSentence(blockNoteFor(iso, b))) : "") +
        (b.emergency && !off ? '<br><span class="muted">Stuck? ' + esc(firstSentence(b.emergency)) + "</span>" : "") + "</td></tr>";
    });
    h += "</tbody></table>";
    var today = justToday(iso);
    if (today) h += "<h2>Today only</h2>" + today;
    h += groupsHTML(iso, true);                                   /* v89 */
    h += '<div class="two" style="margin-top:14pt">';
    if (S.watch.length) {
      h += '<div><h2 style="margin-top:0">Keep an eye on</h2>' +
        S.watch.map(function (w) { return "<p><b>" + esc(w.name) + "</b> " + esc(firstSentence(w.note)) + "</p>"; }).join("") + "</div>";
    }
    if (S.consequences || S.incentives) {
      h += '<div><h2 style="margin-top:0">Behaviour, briefly</h2>' +
        (S.consequences ? "<p>" + esc(firstSentence(S.consequences)) + "</p>" : "") +
        (S.incentives ? '<p class="muted">' + esc(firstSentence(S.incentives)) + "</p>" : "") + "</div>";
    }
    h += "</div>";
    if (S.trusted) h += "<p><b>Ask these students if unsure:</b> " + esc(S.trusted) + "</p>";
    return h;
  }

    return { buildFull: buildFull, buildGlance: buildGlance, DOC_CSS: DOC_CSS, pretty: pretty };
  }
  const api = { make };
  if (typeof module !== 'undefined') module.exports = api;
  if (typeof window !== 'undefined') window.SuiteSubV95 = api;
})();
