// Copies v95's sub plan printouts out of its sub-plans.js, unchanged, into core/subplan-v95.js.
// The copied functions read the day through blocksFor, lessonFor, dayNote, dayFlags,
// dayBlockNotes, blockNoteFor, bkey, mathBoard and S, which core/subplan.js supplies from
// the new planner's records. Run: node tools/extract-subplan.js <path to v95 sub-plans.js>
const fs = require('fs');
const path = require('path');
const src = fs.readFileSync(process.argv[2], 'utf8');
function fn(name) {
  const a = src.indexOf(`  function ${name}(`);
  if (a < 0) throw new Error('no function ' + name);
  // A function ends where the next top-level statement (two-space indent) begins.
  const rest = src.slice(a + 10);
  const m = /\n  (?:function |var |\/\*|\/\/|document\.|window\.|if \(|return )/.exec(rest);
  return src.slice(a, m ? a + 10 + m.index : undefined).replace(/\s+$/, '') + '\n';
}
function constLine(name) {
  const m = new RegExp(`  var ${name} = [^;]+;`).exec(src);
  if (!m) throw new Error('no var ' + name);
  return m[0];
}
function block(start) {   // a multi-line var, up to the next top-level statement
  const a = src.indexOf(start);
  if (a < 0) throw new Error('no ' + start);
  const m = /\n  (?:function |var |\/\*|\/\/)/.exec(src.slice(a + 10));
  return src.slice(a, a + 10 + m.index).replace(/\s+$/, '') + '\n';
}
const names = ['esc', 'nl', 'dayKeyOf', 'pretty', 'when', 'justToday', 'specialFor', 'firstSentence', 'groupsHTML', 'buildFull', 'buildGlance'];
const body = [constLine('DAYS'), constLine('MONTHS'), constLine('DAYKEY'), block('  var DOC_CSS ='), ...names.map(fn)].join('\n');
const out = `// GENERATED by tools/extract-subplan.js from v95's sub-plans.js. Do not edit by hand.
// v95's sub plan printouts, copied unchanged. make(env) gives them the day's data (see core/subplan.js).
(function () {
  function make(env) {
    var S = env.S, blocksFor = env.blocksFor, lessonFor = env.lessonFor, dayNote = env.dayNote, dayFlags = env.dayFlags,
      dayBlockNotes = env.dayBlockNotes, blockNoteFor = env.blockNoteFor, bkey = env.bkey, mathBoard = env.mathBoard;
    var window = { SuiteWin: env.win || null };
${body}
    return { buildFull: buildFull, buildGlance: buildGlance, DOC_CSS: DOC_CSS, pretty: pretty };
  }
  const api = { make };
  if (typeof module !== 'undefined') module.exports = api;
  if (typeof window !== 'undefined') window.SuiteSubV95 = api;
})();
`;
fs.writeFileSync(path.join(__dirname, '..', 'core', 'subplan-v95.js'), out);
console.log('wrote core/subplan-v95.js', out.length, 'bytes');
