// Copies v95's family-email language (tables and pure functions) out of its curriculum.js,
// unchanged, into core/family-v95.js. Run: node tools/extract-family.js <path to v95 curriculum.js>
const fs = require('fs');
const path = require('path');
const src = fs.readFileSync(process.argv[2], 'utf8');
const cut = (from, to) => {
  const a = src.indexOf(from), b = src.indexOf(to, a);
  if (a < 0 || b < 0) throw new Error(`could not find ${from} … ${to}`);
  return src.slice(a, b);
};
const body = [
  cut('  function famPhrase(t)', '  function goalStore()'),
  cut('  function parseSpelling(t)', '  function saveSpelling(')
].join('\n');
const out = `// GENERATED by tools/extract-family.js from v95's curriculum.js. Do not edit by hand.
// v95's family-email language: the plain phrase for each Reveal lesson (FAM_MATH), the
// reading strategies and skills in families' words (FAM_META, FAM_COMP), the line merging
// (famSummary), and the spelling-list reader. Copied, not retyped, so the wording is v95's.
(function () {
${body}
  const api = { famPhrase, uniq, famMath, famSummary, famLookup, famComp, famGoalOptions, famGoalDefault, parseSpelling, spellLine, FAM_MATH, FAM_META, FAM_COMP };
  if (typeof module !== 'undefined') module.exports = api;
  if (typeof window !== 'undefined') window.SuiteFamilyV95 = api;
})();
`;
fs.writeFileSync(path.join(__dirname, '..', 'core', 'family-v95.js'), out);
console.log('wrote core/family-v95.js', out.length, 'bytes');
